//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobLogger.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMessage
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int IdType { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
