//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobLogger.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobLoggerEntities : DbContext
    {
        public JobLoggerEntities()
            : base("name=JobLoggerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogMessage> LogMessage { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<LogConfiguration> LogConfiguration { get; set; }
    }
}
